language: objective-c
osx_image: xcode11.6

before_script:
    - carthage bootstrap

script:
    # Build Travis project and run tests
    - xcodebuild -project LibreTransmitter.xcodeproj -scheme Shared build -destination name="iPhone 8" test 
